import relaxed from "./relaxed.json";
import relaxedSafestop from "./relaxed-safestop.json";
import focused from "./focused.json";
import gamma from "./gamma.json";
import { BundleSchema, type EvidenceBundle } from "../schemas/evidence";

/**
 * Bundled, immutable demo evidence (ADR-0014 §13) — real artifacts generated by
 * `ruv-neural neuromod --bundle … --sign`, validated at module load so a
 * malformed fixture fails the build rather than the runtime.
 */
export interface DemoPreset {
  id: string;
  label: string;
  description: string;
  target: "relaxed" | "focused" | "gamma";
  perturbation: number | null;
  bundle: EvidenceBundle;
}

function load(raw: unknown): EvidenceBundle {
  return BundleSchema.parse(raw);
}

export const DEMO_PRESETS: DemoPreset[] = [
  {
    id: "relaxed",
    label: "Relaxed — converge",
    description:
      "Drive toward a calm/relaxed state with 40 Hz audio+haptic. The loop titrates conservatively and completes when the response holds at target.",
    target: "relaxed",
    perturbation: null,
    bundle: load(relaxed),
  },
  {
    id: "relaxed-safestop",
    label: "Relaxed — fail-safe stop",
    description:
      "Same target, but an arousal spike is injected mid-session. The response leaves the safety envelope and the loop performs a fail-safe stop (intensity → 0).",
    target: "relaxed",
    perturbation: 5,
    bundle: load(relaxedSafestop),
  },
  {
    id: "focused",
    label: "Focused — 40 Hz entrainment",
    description:
      "A focused-attention target with 40 Hz gamma entrainment (audio+haptic).",
    target: "focused",
    perturbation: null,
    bundle: load(focused),
  },
  {
    id: "gamma",
    label: "Gamma — multimodal (screened)",
    description:
      "Pure 40 Hz GENUS entrainment across light+audio+haptic. Light is enabled because a photosensitivity screen is cleared.",
    target: "gamma",
    perturbation: null,
    bundle: load(gamma),
  },
];

export function presetById(id: string): DemoPreset | undefined {
  return DEMO_PRESETS.find((p) => p.id === id);
}
